### ISSUE TITLE
Transactions-Custom category

### ISSUE THREAD

**Issue by Joice-craysol** [midhun-craysol/erpx#20]
Refresh button->Design issues.
All sorting arrows should inside the data table.
Show Entries->"Entries" First letter should be capital.
Validation message->All validation messages first letter should be capital in each word. And also mention which field is to be required.
Add->Save button move to right side (Fully congested).
Alert box->erp should be capital,And project name and the green tick should be same alignment.
Edit cannot working.
Delete->Project name and the trash box should be same alignmnet.

**Comment by vyshu-craysol** [comment]
All sorting arrows should inside the data table.-Done
Show Entries->"Entries" First letter should be capital.-Done
Validation message->All validation messages first letter should be capital in each word. And also mention which field is to be required.-Done
Alert box->erp should be capital,And project name and the green tick should be same alignment.
Edit cannot working.-Done
Delete->Project name and the trash box should be same alignment.-Done
